### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by sdandey** [cwaldbieser/jhub_remote_user_authenticator#17]
Hi, 

I made modifications to the code and created a distribution using "python sdist" command which created jhub_remote_user_authenticator-0.1.2.tar.gz.

When I try install this via pip I get following error.  Any idea on how to resolve this issue?

```
Processing /tmp/jhub_remote_user_authenticator-0.1.2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-i0t6gphl/setup.py", line 23, in <module>
        with open(pjoin(here, 'version.py')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-i0t6gphl/version.py'
```

**Comment by cwaldbieser** [comment]
It looks like the `version.py` file used for specifying the release version isn't included in `setup.py`.  I think I could probably include it by adding it to the `package_data` or `data_files` arguments to `setup.py`.

**Comment by cwaldbieser** [comment]
I just pushed commit 375972b to master.  I *think* that should take care of it.  If you are still having trouble, let me know.

**Comment by cwaldbieser** [comment]
@sdandey - Did that resolve your issue?
